services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  backend:
    build: .
    command: uvicorn app.api.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app              # Mappa il codice per il reload in tempo reale
      - ./data:/app/data    # Salva i dati SQLite e i JSON estratti sul PC
      - ./logs:/app/logs    # Salva i log sul PC
    env_file:
      - .env                # INIETTA LE CREDENZIALI HUBSPOT
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.tasks.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env                # INIETTA LE CREDENZIALI HUBSPOT
    depends_on:
      - redis

volumes:
  redis_data: